mysite/blog/urls.py
from django.urls import path

from . import views
from .feeds import AllPostsRssFeed


app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('index', views.index, name='index'),
    path('posts/<int:id>',views.post, name='post'),
    path('tags/<int:id>',views.tag, name='tag'),
    path('categories/<int:id>',views.category, name='category'),
    path('archives', views.archives,  name='archives'),
    path('atom.xml', AllPostsRssFeed(), name='rss')
    # path('archives/', views.archives, name='archives'),
    # path('about/', views.about, 'about')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_count(self):
        return Post.objects.filter(category = self).count()

    def get_posts(self):
        return Post.objects.filter(category = self)

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_count(self):
        return Post.objects.filter(tags = self).count()

    def get_posts(self):
        return Post.objects.filter(tags = self)


class Post(models.Model):
    title = models.CharField(max_length=200)
    # body = models.TextField()
    body = MDTextField()

    created_time = models.DateTimeField(default=timezone.now)
    modified_time = models.DateTimeField(auto_now=True)

    # excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User, models.PROTECT)

    # click number
    clicks = models.IntegerField(default=0)

    def __str__(self):
        return self.title

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage, EmptyPage, PageNotAnInteger

from django.views import generic
from .models import Category, Tag, Post

import markdown
# Create your views here.

page_count = 5
timeline_count = 15
def get_tags():
    return Tag.objects.all();

def get_categories():
    return Category.objects.all();

def home(request):
    context = {}
    return render(request, 'blog/home.html', context=context)

def index(request):
    paginator = Paginator(Post.objects.all().order_by('-created_time'), page_count)

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except (InvalidPage, EmptyPage):
        post_list = paginator.page(paginator.num_pages)

    context = {
        'post_list': post_list,
        'tags': get_tags(),
        'categories': get_categories(),
    }

    return render(request, 'blog/index.html', context=context)


def post(request, id):
    post = get_object_or_404(Post, pk=id)
    ext = [
        'markdown.extensions.extra',
        # 'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ]
    post.clicks += 1
    post.save()
    post.body = markdown.markdown(post.body, extensions=ext, safe_mode=True)
    context = {
        'title': post.title,
        'post': post,
        'tags': get_tags(),
        'categories': get_categories(),
    }
    return render(request, 'blog/post.html', context=context)


def tag(request, id):
    tag = get_object_or_404(Tag, pk=id)
    paginator = Paginator(tag.get_posts().order_by('-created_time'), page_count)

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except (InvalidPage, EmptyPage):
        post_list = paginator.page(paginator.num_pages)

    context = {
        'title': 'Tags -- %s' % tag.name,
        'post_list': post_list,
        'tags': get_tags(),
        'categories': get_categories(),
    }

    return render(request, 'blog/index.html', context=context)

def category(request, id):
    category = get_object_or_404(Category, pk=id)
    paginator = Paginator(category.get_posts().order_by('-created_time'), 3)

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except (InvalidPage, EmptyPage):
        post_list = paginator.page(paginator.num_pages)

    context = {
        'title': 'Category -- %s' % category.name,
        'post_list': post_list,
        'tags': get_tags(),
        'categories': get_categories(),
    }

    return render(request, 'blog/index.html', context=context)


def archives(request):
    paginator = Paginator(Post.objects.all().order_by('-created_time'), timeline_count)

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except (InvalidPage, EmptyPage):
        post_list = paginator.page(paginator.num_pages)

    context = {
        'hero': False,
        'title': 'Archives',
        'post_list': post_list,
        'tags': get_tags(),
        'categories': get_categories(),
    }

    return render(request, 'blog/archives.html', context=context)    


def about(request):
    return render(request, 'blog/index.html', context={'title': 'about'})

mysite/blog/templates/blog/_categories.html
<div class="card mr-1">
  <header class="card-header">
    <div class="card-header-title">
      <p>
        <span class="icon"><i class="fas fa-th-large"></i></span>
        Categories
      </p>
    </div>
  </header>
  <div class="card-content is-paddingless">
    <div class="panel">
      {% for category in categories %}

      <!--  -->
      <a class="panel-block" href="{% url 'blog:category' category.id %}">
        {{ category.name }}&nbsp;
        <span class="tag is-rounded">{{ category.get_count }}</span>
      </a>
      {% endfor %}
    </div>
  </div>
</div>

mysite/blog/templates/blog/_footer.html
<footer class="footer">
  <div class="content has-text-centered">
    Copyright &copy; 2017-2019 wuxiaobai24.fun. All Rights Reserved
    <br>
    <a target="_blank" rel="nofollow noopener" href="http://beian.miitbeian.gov.cn/">粤 ICP 备 19101717 号</a>
    <br>
    Powered by <a href="https://www.djangoproject.com/" target="_blank">Django</a> & <a href="https://bulma.io/" target="_blank">Bulma</a>
  </div>
</footer>

mysite/blog/templates/blog/_header.html
{% load static %}
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {% if title %}
  <title>Code &amp; Fun -- {{ title }}</title>
  {% else %}
  <title>Code &amp; Fun</title>
  {% endif %}
  
  <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" />
  <link
    rel="stylesheet"
    href="{% static 'blog/css/bulma.min.css' %}"
  />
  <link href="{% static 'blog/css/bulma-timeline.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/bulma-badge.min.css' %}" rel="stylesheet">
  <link
    href="https://fonts.googleapis.com/css?family=Pacifico&display=swap"
    rel="stylesheet"
  />
  <link href="{% static 'blog/css/github.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/typo.css' %}" rel="stylesheet">
  <script
    defer
    src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
  ></script>
  <script src="{% static 'blog/js/highlight.pack.js' %}"></script>
</head>

mysite/blog/templates/blog/_navbar.html
<!-- navbar -->
<header
  class="navbar is-fixed-top"
  role="navigation"
  aria-label="main navigation"
>
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'blog:home' %}">
      <p style="font-family: 'Pacifico', cursive">Code &amp; Fun</p>
    </a>

    <a
      role="button"
      class="navbar-burger burger"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbarBasic"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasic" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'blog:index' %}"
        ><span class="icon"><i class="fas fa-home"></i></span>&nbsp;Home</a
      >
      <a class="navbar-item" href="{% url 'blog:archives' %}"
        ><span class="icon"><i class="fas fa-archive"></i></span
        >&nbsp;Archives</a
      >
      <!-- <a class="navbar-item" href="{% url 'blog:index' %}"
        ><span class="icon"><i class="fa fa-th-large"></i></span
        >&nbsp;Categories</a
      > -->
      <!-- <a class="navbar-item"
        ><span class="icon"><i class="fa fa-tags"></i></span>&nbsp;Tags</a
      > -->
      <a class="navbar-item" href="{% url 'blog:index' %}"
        ><span class="icon"><i class="fas fa-user"></i></span>&nbsp;About Me</a
      >
    </div>
  </div>
</header>

mysite/blog/templates/blog/_tags.html
<div class="card mr-1">
  <header class="card-header">
    <div class="card-header-title">
      <p>
        <span class="icon"><i class="fas fa-tags"></i></span> Tags
      </p>
    </div>
  </header>
  <div class="card-content">
    <div class="tags">
      {% for tag in tags %}
      <span class="tag">
        <a href="{% url 'blog:tag' tag.id %}">
          <span class="icon"><i class="fas fa-tag"></i></span>
          &nbsp;{{ tag.name }}
        </a>
      </span>
      {% endfor %}
    </div>
  </div>
</div>

mysite/blog/templates/blog/archives.html
{% extends "blog/base.html" %} 
{% block content %}

<div class="box">
  <!-- timeline -->
  <div class="timeline is-centered">
    {% for post in post_list %}
    <div class="timeline-item">
      <div class="timeline-marker"></div>
      <div class="timeline-content">
        <div class="heading">{{ post.created_time }}</div>
        <a href="{% url 'blog:post' post.id %}">{{ post.title }}</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- pagination -->
<nav class="pagination is-rounded" role="pagination">
  {% if post_list.has_previous %}
  <a
    class="pagination-previous"
    href="?page={{ post_list.previous_page_numer }}"
  >
    Previous
  </a>
  {% endif %} {% if post_list.has_next %}
  <a class="pagination-next" href="?page={{ post_list.next_page_number }}">
    Next Page
  </a>
  {% endif %}
</nav>

{% endblock content %}

mysite/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <!-- header -->
  {% include "blog/_header.html" %}
  <body>
    <!-- navbar -->
    
    {% include "blog/_navbar.html" %}
    <!-- hero
    {% if hero %}
    {% include "blog/_hero.html" %}  
    {% endif %} -->

    <!-- main -->
    <section class="section">
      <div class="container is-fullhd">
        <div class="columns">
          <!-- main content -->
          <div class="column is-8">
            <!-- notification -->
            {% if message %}
            <div class="notification">
              <button class="delete"></button>
              <p>{{ message }}</p>
            </div>
            {% endif %}

            <!-- main content -->
            {% block content %} {% endblock content %}
          </div>

          <!-- aside -->
          <aside class="column is-4 is-narrow">
            <!-- Category -->
            {% include "blog/_categories.html" with categories=categories %}
            <!-- Tags -->
            {% include "blog/_tags.html" with tags=tags %}
          </aside>
        </div>
      </div>
    </section>

    <!-- footer -->
    {% include "blog/_footer.html" %}
  </body>

  <!-- for navbar -->
  <script src="{% static 'blog/js/main.js' %}"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
</html>

mysite/blog/templates/blog/home.html
{% load static %}

<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <!-- header -->
  {% include "blog/_header.html" %}
  <body>
    <!-- navbar -->
    
    {% include "blog/_navbar.html" %}
    <!-- hero -->
    <!-- hero -->
	<section class="hero is-fullheight-with-navbar">
		<div class="hero-body">
		<div class="container">
			<p class="title has-text-centered">
			Keep It Simple, Stupid.
			</p>
			<div class="title has-text-centered">
				<span class="icon is-large">
					<a href="https://github.com/wuxiaobai24">
					<i class="fab fa-github"></i>
					</a>
				</span>
				<span class="icon is-large">
					<a href="wuxiaobai24:wuxiaobai24@foxmail.com">
					<i class="far fa-envelope"></i>
					</a>
				</span>
				<span class="icon is-large">
					<a href="https://wuxiaobai24.github.io">
					<i class="far fa-paper-plane"></i>
					</a>
				</span>
				<span class="icon is-large">
					<a href="{% url 'blog:rss' %}">
					<i class="fas fa-rss"></i>
					</a>
				</span>
			</div>
		</div>
		</div>
	</section>

    <!-- main -->

    <!-- footer -->
    {% include "blog/_footer.html" %}
  </body>

  <!-- for navbar -->
  <script src="{% static 'blog/js/main.js' %}"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
</html>

mysite/blog/templates/blog/index.html
{% extends "blog/base.html" %} 
{% block content %} 
{% for post in post_list %}
<div class="box">
  <div class="content">
    <!-- header -->
    <a href="{% url 'blog:post' post.id %}"><h2>{{ post.title }}</h2></a>
    

    <div class="level">
      <div class="level-left">
        <span class="level-item is-mobile">
          <span class="icon"><i class="far fa-clock"></i></span>
          <p>{{ post.created_time }}</p>
        </span>

        <span class="level-item">
          <span class="icon"><i class="far fa-eye"></i></span>
          <p>{{ post.clicks }}</p>
        </span>
        
        <a class="level-item tags has-addons" href="{% url 'blog:category' post.category.id %}">
          <span class="tag">{{ post.category.name }}</span>
          <span class="tag is-primary">{{ post.category.get_count }}</span>
        </a>
      </div>
      <div class="level-right">
        <!-- tags -->

        <div class="tags">
          {% for tag in post.tags.all %}
          <span class="tag level-item">
            
            <a href="{% url 'blog:tag' tag.id %}">
              <span class="icon"><i class="fas fa-tag"></i></span>
              &nbsp;{{ tag.name }}
            </a>
          </span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<!-- pagination -->
<nav class="pagination is-rounded" role="pagination">
  {% if post_list.has_previous %}
  <a
    class="pagination-previous"
    href="?page={{ post_list.previous_page_numer }}"
  >
    Previous
  </a>
  {% endif %} 
  {% if post_list.has_next %}
  <a class="pagination-next" href="?page={{ post_list.next_page_number }}">
    Next Page
  </a>
  {% endif %}
</nav>

{% endblock content %}

mysite/blog/templates/blog/post.html
{% extends "blog/base.html" %} {% block content %}
<div class="box">
  <div>
    <h1 class="title has-text-centered">{{ post.title }}</h1>
    <div class="level">
      <div class="level-left">
        <span class="level-item is-mobile">
          <span class="icon"><i class="far fa-clock"></i></span>
          <p>{{ post.created_time }}</p>
        </span>
        <span class="level-item">
          <span class="icon"><i class="far fa-eye"></i></span>
          <p>{{ post.clicks }}</p>
        </span>
        <a class="level-item tags has-addons" href="#">
          <span class="tag">{{ post.category.name }}</span>
          <span class="tag is-primary">{{ post.category.get_count }}</span>
        </a>
      </div>
      <div class="level-right">
        <!-- tags -->
        <div class="tags">
          {% for tag in post.tags.all %}
          <span class="tag level-item">
            <a href="/tag/{{ tag.name }}">
              <span class="icon"><i class="fas fa-tag"></i></span>
              &nbsp;{{ tag.name }}
            </a>
          </span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
<div class="box">
  <div class="content typo">
    {{ post.body | safe }}
  </div>
</div>
{% endblock content %}